### ISSUE TITLE
빌드시 SSR features 오류 

### ISSUE THREAD

**Issue by eodnjs467** [f-lab-edu/netflix-clone#26]
# Amplify 배포시 빌드 오류 발생

route Handler 를 사용해서 오류가 나는건지 .. 원인파악이 잘 안됩니다.

프로젝트 터미널에서 next build 로 빌드시 성공적으로 빌드가 완료됩니다. 
Amplify 에서 배포하려고 하면 빌드시점에서 오류가 나는 상황입니다.

Edge API 라우트로 인해 Next.js 빌드가 실패하는 경우
[참고 링크](https://docs.aws.amazon.com/ko_kr/amplify/latest/userguide/troubleshooting-ssr-deployment.html#nextjs-edge-API-route-not-supported)

```
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2023-10-18T07:13:42.087Z [INFO]: added 373 packages, and audited 374 packages in 13s
2023-10-18T07:13:42.092Z [INFO]: 143 packages are looking for funding
                                 run `npm fund` for details
2023-10-18T07:13:42.119Z [INFO]: 3 vulnerabilities (1 low, 2 moderate)
                                 To address all issues, run:
                                 npm audit fix --force
                                 Run `npm audit` for details.
2023-10-18T07:13:42.131Z [INFO]: # Completed phase: preBuild
2023-10-18T07:13:42.131Z [INFO]: # Starting phase: build
                                 # Executing command: npm run build
2023-10-18T07:13:42.504Z [INFO]: > netflix-clone@0.1.0 build
                                 > next build
2023-10-18T07:13:43.053Z [WARNING]: - warn Invalid next.config.js options detected:
2023-10-18T07:13:43.054Z [WARNING]: - warn     The value at .images has an unexpected property, sizes, which is not in the list of allowed properties (remotePatterns, unoptimized, contentSecurityPolicy, contentDispositionType, dangerouslyAllowSVG, deviceSizes, disableStaticImages, domains, formats, imageSizes, loader, loaderFile, minimumCacheTTL, path).
                                    - warn See more info here: https://nextjs.org/docs/messages/invalid-next-config
2023-10-18T07:13:43.057Z [INFO]: - warn No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2023-10-18T07:13:43.062Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2023-10-18T07:13:43.062Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2023-10-18T07:13:43.140Z [INFO]: - info Creating an optimized production build...
2023-10-18T07:13:53.036Z [INFO]: 
2023-10-18T07:13:53.038Z [INFO]: [35m🌼 daisyUI 3.7.4[0m [0mhttps://daisyui.com
2023-10-18T07:13:53.253Z [INFO]: ╰╮
                                 ╰─ [32m✔︎[0m [2m[ [0m2[2m ][0m themes are enabled. You can add more themes or make your own theme:
                                 https://daisyui.com/docs/themes
                                 [32m    ❤︎ Support daisyUI[0m: https://opencollective.com/daisyui[0m
2023-10-18T07:13:53.253Z [INFO]: 
2023-10-18T07:13:55.174Z [INFO]: - info Compiled successfully
2023-10-18T07:13:55.175Z [INFO]: - info Linting and checking validity of types...
2023-10-18T07:13:57.527Z [INFO]: ./src/components/contents/episode-list.tsx
                                 23:6  Warning: React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
                                 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
2023-10-18T07:13:58.950Z [INFO]: - info Collecting page data...
2023-10-18T07:14:14.904Z [INFO]: - info Generating static pages (0/20)
2023-10-18T07:14:15.112Z [INFO]: - info Generating static pages (5/20)
2023-10-18T07:14:15.181Z [INFO]: - info Generating static pages (10/20)
2023-10-18T07:14:15.267Z [INFO]: - info Generating static pages (15/20)
2023-10-18T07:14:16.034Z [WARNING]: TypeError: Cannot read properties of undefined (reading 'map')
                                    at CardList (/codebuild/output/src1593120314/src/netflix-clone/.next/server/app/browse/page.js:462:45)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:273)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:11)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
                                    at kg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
                                    at mg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:350)
                                    at kg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:215)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
2023-10-18T07:14:16.041Z [WARNING]: Error occurred prerendering page "/browse". Read more: https://nextjs.org/docs/messages/prerender-error
                                    TypeError: Cannot read properties of undefined (reading 'map')
                                    at CardList (/codebuild/output/src1593120314/src/netflix-clone/.next/server/app/browse/page.js:462:45)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:273)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:11)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
                                    at kg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
                                    at mg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:350)
                                    at kg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
                                    at jg (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:215)
                                    at Z (/codebuild/output/src1593120314/src/netflix-clone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
2023-10-18T07:14:16.041Z [INFO]: - info Generating static pages (20/20)
2023-10-18T07:14:16.043Z [WARNING]: > Export encountered errors on following paths:
                                    /browse/page: /browse
2023-10-18T07:14:16.075Z [ERROR]: !!! Build failed
2023-10-18T07:14:16.076Z [INFO]: Please check the supported SSR features to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2023-10-18T07:14:16.076Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-18T07:14:16.076Z [INFO]: # Starting environment caching...
2023-10-18T07:14:16.076Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by eodnjs467** [comment]
/browse/page.ts 에서 getAllContents() 함수를 사용하고 있는데 이 부분에서 map을 사용하고 있긴합니다.
그리고 <CardList />  컴포넌트에서 map을 사용하고 있습니다.
.env 설정떄문에 그런지 .. 한 번 확인 해보겠습니닷

**Comment by eodnjs467** [comment]
빌드 성공했습니다. 
빌드되면서 타입에러에 대한 것 발견
```
2023-10-19T11:36:56.339Z [WARNING]: Failed to set fetch cache https://api.themoviedb.org/3/tv/top_rated?language=ko&page=1 TypeError: fetch failed
                                    at Object.fetch (/codebuild/output/src2106503512/src/netflix-clone/node_modules/next/dist/compiled/undici/index.js:1:26669)
                                    at async globalThis.fetch (/codebuild/output/src2106503512/src/netflix-clone/.next/server/chunks/218.js:8232:16)
                                    at async invokeRequest (/codebuild/output/src2106503512/src/netflix-clone/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
                                    at async invokeIpcMethod (/codebuild/output/src2106503512/src/netflix-clone/node_modules/next/dist/server/lib/server-ipc/request-utils.js:45:21)
                                    at async /codebuild/output/src2106503512/src/netflix-clone/.next/server/chunks/218.js:8430:29 {
                                    cause: SocketError: other side closed
                                    at Socket.onSocketEnd (/codebuild/output/src2106503512/src/netflix-clone/node_modules/next/dist/compiled/undici/index.js:1:63301)
                                    at Socket.emit (node:events:525:35)
                                    at endReadableNT (node:internal/streams/readable:1358:12)
                                    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
                                    code: 'UND_ERR_SOCKET',
                                    socket: {
                                    localAddress: '127.0.0.1',
                                    localPort: 34230,
                                    remoteAddress: '127.0.0.1',
                                    remotePort: 34919,
                                    remoteFamily: 'IPv4',
                                    timeout: undefined,
                                    bytesWritten: 27239,
                                    bytesRead: 246
                                    }
                                    }
                                    }
```

**Comment by eodnjs467** [comment]
환경 변수 설정을 통해 로컬에서 사용하는 변수의 값을 지정해줌으로서 해결하였고 빌드 후  배포 완료 했습니다.
